CREATE TABLE `TEST_AUTHORS` (
  `ID`         VARCHAR(255) NOT NULL,
  `LASTNAME`   VARCHAR(50) DEFAULT NULL,
  `middlename` VARCHAR(50) DEFAULT NULL,
  `NAME`       VARCHAR(50)  NOT NULL,
  PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE `TEST_BOOKS` (
  `ID`        VARCHAR(255) NOT NULL,
  `NAME`      VARCHAR(50)  NOT NULL,
  `YEAR`      INT(11)      NOT NULL,
  `AUTHOR_ID` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK7A7694BDFCECE03A` (`AUTHOR_ID`),
  CONSTRAINT `FK7A7694BDFCECE03A` FOREIGN KEY (`AUTHOR_ID`) REFERENCES `TEST_AUTHORS` (`ID`),
  CONSTRAINT `FKh2voxnppe2d3gf5fwm50dpbxn` FOREIGN KEY (`AUTHOR_ID`) REFERENCES `TEST_AUTHORS` (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE `SHOP_CATEGORY` (
  `ID`          VARCHAR(255) NOT NULL,
  `NAME_`       TEXT         DEFAULT NULL,
  `DESCRIPTION` TEXT         DEFAULT NULL,
  `LEVEL_`      INT(11)      NOT NULL,
  `PARENT_ID`   VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK1A7694BDFCECF034` (`PARENT_ID`),
  CONSTRAINT `FK1A7694BDFCECF034` FOREIGN KEY (`PARENT_ID`) REFERENCES `SHOP_CATEGORY` (`ID`),
  CONSTRAINT `FKh2voxnppe2d4gf3fwm11dpbxn` FOREIGN KEY (`PARENT_ID`) REFERENCES `SHOP_CATEGORY` (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE `SHOP_ITEM` (
  `ID`          VARCHAR(255) NOT NULL,
  `NAME_`       TEXT         DEFAULT NULL,
  `DESCRIPTION` TEXT         DEFAULT NULL,
  `COUNT_`      INT(11)      NOT NULL,
  `CATEGORY_ID` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK7A7694BDFCECF034` (`CATEGORY_ID`),
  CONSTRAINT `FK7A7694BDFCECF034` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `SHOP_CATEGORY` (`ID`),
  CONSTRAINT `FKh2voxnppe2d4gf3fwm10dpbxn` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `SHOP_CATEGORY` (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE `SHOP_USER` (
  `ID`         VARCHAR(255) NOT NULL,
  `NAME_`      TEXT DEFAULT NULL,
  `SURNAME`    TEXT DEFAULT NULL,
  `MIDDLENAME` TEXT DEFAULT NULL,
  `LOGIN`      TEXT DEFAULT NULL,
  `PASSWORD`   TEXT DEFAULT NULL,
  PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;